name: FindBugs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  findbugs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 19
      - name: Run FindBugs
        uses: jvzoggel/findbugs-action@v1
        with:
          source-path: src/main/java
          include-filter: "**/*.java"
          exclude-filter: ""
          low-priority: false
          medium-priority: true
          high-priority: true
          xml-output: true
          html-output: true
          output-directory: "findbugs-reports"
