name: OWASP Dependency Check
on:
  push:
    branches:
      - master
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 19
    - name: Run Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        distribution: auto
        scanpath: .
        format: ALL
        failoncvss: 7
